name: hab_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1
  otp: ^3.1.2
  timezone: ^0.10.1
  base_codecs: ^1.0.1
  google_fonts: ^6.2.1
  circular_countdown_timer: ^0.2.4
  clipboard: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
